# @package _global_
# ADD-3: ADD-0 + ortho_sat (needs is_sat_mask, use_sat=true)
defaults:
  - model: pi3_googlestreet_sat_ablate_add_3.yaml
  - train: train_pi3_lowres_megadepth
  - data: googlestreet_sat.yaml
  - general: googlestreet_sat.yaml
  - extras: default.yaml
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: colorlog
  - _self_

name: saved_runs/add_3
