# @package _global_
# Ablation C lowres
defaults:
  - model: pi3_googlestreet_sat_C1_no_satposembed.yaml
  - train: train_pi3_lowres_megadepth
  - data: googlestreet_sat.yaml
  - general: googlestreet_sat.yaml
  - extras: default.yaml
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: colorlog
  - _self_

name: saved_runs/C1_no_satposembed
